version: '3.3'

networks:
  resnextcloud:
    ipam:
      driver: default
      config:
        - subnet: 172.22.100.0/24
services:
  base:
     image: mysql:5.7
     volumes:
        - /home/ubuntu/compose/ComposeNext/Data/mysql/:/var/lib/mysql/
     networks:
        resnextcloud:
            ipv4_address: 172.22.100.21
            aliases:
             - mysql
             - base
             - bdd
  myadmin: 
    image: phpmyadmin/phpmyadmin
    networks:
      resnextcloud:
         aliases:
          - phpmyadmin
          - pma
          - myadm
    environment:

      PMA_HOST: base
      PMA_ABSOLUTE_URI : /phpMyAdmin
  nginx:
   image: nginx:latest
   networks:
     resnextcloud:
        ipv4_address: 172.22.100.20
        aliases:
         - web
   depends_on:
      - myadmin
      - nextcloud
   ports:
      - "443:443"
   volumes:
      - ./Config/nginx.conf:/etc/nginx/nginx.conf
      - ./Config/cacert.pem:/etc/nginx/certif.crt
      - ./Config/cakey.pem:/etc/nginx/clef.key

  nextcloud:
   image: nextcloud:latest
   depends_on:
      - base
   volumes:
      - ./Data/nextcloud:/var/www/html/data
      - ./Config/nextcloud:/var/www/html/config
   networks:
      resnextcloud:
        aliases:
         - nextcloud
         - files
   environment:
      - NEXTCLOUD_ADMIN_USER=chef
      - NEXTCLOUD_ADMIN_PASSWORD=compose
      - NEXTCLOUD_UPDATE= 1
       

